## Previous Activity

### 1. Import Pandas

In [1]:
#import necessary packages
import pandas as pd

### 2. Import Excel and CSV file

In [19]:
#Load the excel data using pd.read_excel
movies_merge = pd.read_excel("movies_merge.xlsx")

ott_merge = pd.read_csv("ott_merge.csv")

print(movies_merge.columns)

print(ott_merge.columns)

Index(['ID', 'Title', 'Year', 'Age', 'IMDb', 'Rotten Tomatoes', 'Directors',
       'Genres', 'Country', 'Language', 'Runtime'],
      dtype='object')
Index(['ID', 'Netflix', 'Hulu', 'Prime Video', 'Disney+'], dtype='object')

### 3. Validate the DataFrames

In [8]:
# data imported correctly?
print(movies_merge.shape)

movies_merge.head()

(16744, 11)

,ID,Title,Year,Age,IMDb,Rotten Tomatoes,Directors,Genres,Country,Language,Runtime
0,1,Inception,2010,13+,8.8,0.87,Christopher Nolan,"Action,Adventure,Sci-Fi,Thriller","United States,United Kingdom","English,Japanese,French",148.0
1,2,The Matrix,1999,18+,8.7,0.87,"Lana Wachowski,Lilly Wachowski","Action,Sci-Fi",United States,English,136.0
2,3,Avengers: Infinity War,2018,13+,8.5,0.84,"Anthony Russo,Joe Russo","Action,Adventure,Sci-Fi",United States,English,149.0
3,4,Back to the Future,1985,7+,8.5,0.96,Robert Zemeckis,"Adventure,Comedy,Sci-Fi",United States,English,116.0
4,5,"The Good, the Bad and the Ugly",1966,18+,8.8,0.97,Sergio Leone,Western,"Italy,Spain,West Germany",Italian,161.0

In [9]:
# data imported correctly?
print(ott_merge.shape)

ott_merge.head()

(16744, 5)

   ID  Netflix  Hulu  Prime Video  Disney+
0   1        0     0            1        0
1   2        0     1            0        0
2   3        0     0            1        0
3   4        1     0            0        0
4   5        0     0            1        0

### 4. Describe the data types

In [21]:
# data types
print(movies_merge.dtypes)

print(ott_merge.dtypes)

ID                   int64
Title               object
Year                 int64
Age                 object
IMDb               float64
Rotten Tomatoes    float64
Directors           object
Genres              object
Country             object
Language            object
Runtime            float64
dtype: object
ID             int64
Netflix        int64
Hulu           int64
Prime Video    int64
Disney+        int64
dtype: object

### 5. Combine the two DataFrames
#### a) merge()

In [22]:
# merge the data
movies_ott_merge = pd.merge(movies_merge, ott_merge, how = 'left', on = 'ID')

print(movies_ott.shape)

movies_ott.head()

(16744, 15)

,ID,Title,Year,Age,IMDb,Rotten Tomatoes,Directors,Genres,Country,Language,Runtime,Netflix,Hulu,Prime Video,Disney+
0,1,Inception,2010,13+,8.8,0.87,Christopher Nolan,"Action,Adventure,Sci-Fi,Thriller","United States,United Kingdom","English,Japanese,French",148.0,0,0,1,0
1,2,The Matrix,1999,18+,8.7,0.87,"Lana Wachowski,Lilly Wachowski","Action,Sci-Fi",United States,English,136.0,0,1,0,0
2,3,Avengers: Infinity War,2018,13+,8.5,0.84,"Anthony Russo,Joe Russo","Action,Adventure,Sci-Fi",United States,English,149.0,0,0,1,0
3,4,Back to the Future,1985,7+,8.5,0.96,Robert Zemeckis,"Adventure,Comedy,Sci-Fi",United States,English,116.0,1,0,0,0
4,5,"The Good, the Bad and the Ugly",1966,18+,8.8,0.97,Sergio Leone,Western,"Italy,Spain,West Germany",Italian,161.0,0,0,1,0

#### b) concat()

In [17]:
# concat data frames
movies_ott_concat = pd.concat([movies_merge, ott_merge], axis = 0)

print(movies_ott_concat.shape)

movies_ott_concat.head()

(33488, 15)

,ID,Title,Year,Age,IMDb,Rotten Tomatoes,Directors,Genres,Country,Language,Runtime,Netflix,Hulu,Prime Video,Disney+
0,1,Inception,2010.0,13+,8.8,0.87,Christopher Nolan,"Action,Adventure,Sci-Fi,Thriller","United States,United Kingdom","English,Japanese,French",148.0,NaN,NaN,NaN,NaN
1,2,The Matrix,1999.0,18+,8.7,0.87,"Lana Wachowski,Lilly Wachowski","Action,Sci-Fi",United States,English,136.0,NaN,NaN,NaN,NaN
2,3,Avengers: Infinity War,2018.0,13+,8.5,0.84,"Anthony Russo,Joe Russo","Action,Adventure,Sci-Fi",United States,English,149.0,NaN,NaN,NaN,NaN
3,4,Back to the Future,1985.0,7+,8.5,0.96,Robert Zemeckis,"Adventure,Comedy,Sci-Fi",United States,English,116.0,NaN,NaN,NaN,NaN
4,5,"The Good, the Bad and the Ugly",1966.0,18+,8.8,0.97,Sergio Leone,Western,"Italy,Spain,West Germany",Italian,161.0,NaN,NaN,NaN,NaN

#### c) append()

In [18]:
# append data frames
movies_ott_append = movies_merge.append(ott_merge)

print(movies_ott_append.shape)

movies_ott_append.head()

(33488, 15)

,ID,Title,Year,Age,IMDb,Rotten Tomatoes,Directors,Genres,Country,Language,Runtime,Netflix,Hulu,Prime Video,Disney+
0,1,Inception,2010.0,13+,8.8,0.87,Christopher Nolan,"Action,Adventure,Sci-Fi,Thriller","United States,United Kingdom","English,Japanese,French",148.0,NaN,NaN,NaN,NaN
1,2,The Matrix,1999.0,18+,8.7,0.87,"Lana Wachowski,Lilly Wachowski","Action,Sci-Fi",United States,English,136.0,NaN,NaN,NaN,NaN
2,3,Avengers: Infinity War,2018.0,13+,8.5,0.84,"Anthony Russo,Joe Russo","Action,Adventure,Sci-Fi",United States,English,149.0,NaN,NaN,NaN,NaN
3,4,Back to the Future,1985.0,7+,8.5,0.96,Robert Zemeckis,"Adventure,Comedy,Sci-Fi",United States,English,116.0,NaN,NaN,NaN,NaN
4,5,"The Good, the Bad and the Ugly",1966.0,18+,8.8,0.97,Sergio Leone,Western,"Italy,Spain,West Germany",Italian,161.0,NaN,NaN,NaN,NaN

## New activity starts from here (Practical Activity 3.1.10)

### Prepare your workstation

In [1]:
# import pandas
import pandas as pd

# load the excel data using pd.read_excel
movies = pd.read_excel("movies_merge.xlsx")

# load the csv data using pd.read_csv
ott = pd.read_csv("ott_merge.csv")

# data imported correctly?
print(movies.columns)
print(movies.shape)
print(ott.columns)
print(ott.shape)

#merge the data
mov_ott = pd.merge(movies, ott, how='left', on = "ID")

# DataFrames merged correctly?
print(mov_ott.columns)
print(mov_ott.shape)

Index(['ID', 'Title', 'Year', 'Age', 'IMDb', 'Rotten Tomatoes', 'Directors',
       'Genres', 'Country', 'Language', 'Runtime'],
      dtype='object')
(16744, 11)
Index(['ID', 'Netflix', 'Hulu', 'Prime Video', 'Disney+'], dtype='object')
(16744, 5)
Index(['ID', 'Title', 'Year', 'Age', 'IMDb', 'Rotten Tomatoes', 'Directors',
       'Genres', 'Country', 'Language', 'Runtime', 'Netflix', 'Hulu',
       'Prime Video', 'Disney+'],
      dtype='object')
(16744, 15)

In [2]:
# view data frame
mov_ott

,ID,Title,Year,Age,IMDb,Rotten Tomatoes,Directors,Genres,Country,Language,Runtime,Netflix,Hulu,Prime Video,Disney+
0,1,Inception,2010,13+,8.8,0.87,Christopher Nolan,"Action,Adventure,Sci-Fi,Thriller","United States,United Kingdom","English,Japanese,French",148.0,0,0,1,0
1,2,The Matrix,1999,18+,8.7,0.87,"Lana Wachowski,Lilly Wachowski","Action,Sci-Fi",United States,English,136.0,0,1,0,0
2,3,Avengers: Infinity War,2018,13+,8.5,0.84,"Anthony Russo,Joe Russo","Action,Adventure,Sci-Fi",United States,English,149.0,0,0,1,0
3,4,Back to the Future,1985,7+,8.5,0.96,Robert Zemeckis,"Adventure,Comedy,Sci-Fi",United States,English,116.0,1,0,0,0
4,5,"The Good, the Bad and the Ugly",1966,18+,8.8,0.97,Sergio Leone,Western,"Italy,Spain,West Germany",Italian,161.0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16739,16740,The Ghosts of Buxley Hall,1980,NaN,6.2,NaN,Bruce Bilson,"Comedy,Family,Fantasy,Horror",United States,English,120.0,0,0,1,0
16740,16741,The Poof Point,2001,7+,4.7,NaN,Neal Israel,"Comedy,Family,Sci-Fi",United States,English,90.0,0,0,1,0
16741,16742,Sharks of Lost Island,2013,NaN,5.7,NaN,Neil Gelinas,Documentary,United States,English,NaN,0,0,1,0
16742,16743,Man Among Cheetahs,2017,NaN,6.6,NaN,Richard Slater-Jones,Documentary,United States,English,NaN,0,0,1,0
16743,16744,In Beaver Valley,1950,NaN,NaN,NaN,James Algar,"Documentary,Short,Family",United States,English,32.0,1,0,0,0

### 1: The film release date and content rating

In [3]:
# Determine movies per year and age group
movies.pivot(index = 'Title', columns = 'Age', values = 'Year')

Age                                NaN     13+  16+     18+      7+  all
Title
Inception                          NaN  2010.0  NaN     NaN     NaN  NaN
The Matrix                         NaN     NaN  NaN  1999.0     NaN  NaN
Avengers: Infinity War             NaN  2018.0  NaN     NaN     NaN  NaN
Back to the Future                 NaN     NaN  NaN     NaN  1985.0  NaN
The Good, the Bad and the Ugly     NaN     NaN  NaN  1966.0     NaN  NaN
...                                ...     ...  ...     ...     ...  ...
The Ghosts of Buxley Hall       1980.0     NaN  NaN     NaN     NaN  NaN
The Poof Point                     NaN     NaN  NaN     NaN  2001.0  NaN
Sharks of Lost Island           2013.0     NaN  NaN     NaN     NaN  NaN
Man Among Cheetahs              2017.0     NaN  NaN     NaN     NaN  NaN
In Beaver Valley                1950.0     NaN  NaN     NaN     NaN  NaN

[16744 rows x 6 columns]

### 2: The title of movies, the directors, and genres by content rating

In [4]:
# Determine movies, directors and genres per age group
movies.pivot(index = 'Title', columns = 'Age', 
             values = ['Directors', 'Genres'])

                                           Directors                           \
Age                                              NaN                      13+
Title
Inception                                        NaN        Christopher Nolan
The Matrix                                       NaN                      NaN
Avengers: Infinity War                           NaN  Anthony Russo,Joe Russo
Back to the Future                               NaN                      NaN
The Good, the Bad and the Ugly                   NaN                      NaN
...                                              ...                      ...
The Ghosts of Buxley Hall               Bruce Bilson                      NaN
The Poof Point                                   NaN                      NaN
Sharks of Lost Island                   Neil Gelinas                      NaN
Man Among Cheetahs              Richard Slater-Jones                      NaN
In Beaver Valley                         James Algar                      NaN

                                                                     \
Age                             16+                             18+
Title
Inception                       NaN                             NaN
The Matrix                      NaN  Lana Wachowski,Lilly Wachowski
Avengers: Infinity War          NaN                             NaN
Back to the Future              NaN                             NaN
The Good, the Bad and the Ugly  NaN                    Sergio Leone
...                             ...                             ...
The Ghosts of Buxley Hall       NaN                             NaN
The Poof Point                  NaN                             NaN
Sharks of Lost Island           NaN                             NaN
Man Among Cheetahs              NaN                             NaN
In Beaver Valley                NaN                             NaN

                                                      \
Age                                          7+  all
Title
Inception                                   NaN  NaN
The Matrix                                  NaN  NaN
Avengers: Infinity War                      NaN  NaN
Back to the Future              Robert Zemeckis  NaN
The Good, the Bad and the Ugly              NaN  NaN
...                                         ...  ...
The Ghosts of Buxley Hall                   NaN  NaN
The Poof Point                      Neal Israel  NaN
Sharks of Lost Island                       NaN  NaN
Man Among Cheetahs                          NaN  NaN
In Beaver Valley                            NaN  NaN

                                                      Genres  \
Age                                                      NaN
Title
Inception                                                NaN
The Matrix                                               NaN
Avengers: Infinity War                                   NaN
Back to the Future                                       NaN
The Good, the Bad and the Ugly                           NaN
...                                                      ...
The Ghosts of Buxley Hall       Comedy,Family,Fantasy,Horror
The Poof Point                                           NaN
Sharks of Lost Island                            Documentary
Man Among Cheetahs                               Documentary
In Beaver Valley                    Documentary,Short,Family

                                                                       \
Age                                                          13+  16+
Title
Inception                       Action,Adventure,Sci-Fi,Thriller  NaN
The Matrix                                                   NaN  NaN
Avengers: Infinity War                   Action,Adventure,Sci-Fi  NaN
Back to the Future                                           NaN  NaN
The Good, the Bad and the Ugly                               NaN  NaN
...                                                          ...  ...
The Ghosts of Buxley Hall                                    NaN  NaN
The Poof Point                                               NaN  NaN
Sharks of Lost Island                                        NaN  NaN
Man Among Cheetahs                                           NaN  NaN
In Beaver Valley                                             NaN  NaN


Age                                       18+                       7+  all
Title
Inception                                 NaN                      NaN  NaN
The Matrix                      Action,Sci-Fi                      NaN  NaN
Avengers: Infinity War                    NaN                      NaN  NaN
Back to the Future                        NaN  Adventure,Comedy,Sci-Fi  NaN
The Good, the Bad and the Ugly        Western                      NaN  NaN
...                                       ...                      ...  ...
The Ghosts of Buxley Hall                 NaN                      NaN  NaN
The Poof Point                            NaN     Comedy,Family,Sci-Fi  NaN
Sharks of Lost Island                     NaN                      NaN  NaN
Man Among Cheetahs                        NaN                      NaN  NaN
In Beaver Valley                          NaN                      NaN  NaN

[16744 rows x 12 columns]

### 3: The title of movies, the released year, and language by content rating

In [6]:
# Determine movies, year and language per age group
movies.pivot(index = 'Title', columns = 'Age', 
             values = ['Year', 'Language'])

                                Year                             Language  \
Age                              NaN   13+  16+   18+    7+  all      NaN
Title
Inception                        NaN  2010  NaN   NaN   NaN  NaN      NaN
The Matrix                       NaN   NaN  NaN  1999   NaN  NaN      NaN
Avengers: Infinity War           NaN  2018  NaN   NaN   NaN  NaN      NaN
Back to the Future               NaN   NaN  NaN   NaN  1985  NaN      NaN
The Good, the Bad and the Ugly   NaN   NaN  NaN  1966   NaN  NaN      NaN
...                              ...   ...  ...   ...   ...  ...      ...
The Ghosts of Buxley Hall       1980   NaN  NaN   NaN   NaN  NaN  English
The Poof Point                   NaN   NaN  NaN   NaN  2001  NaN      NaN
Sharks of Lost Island           2013   NaN  NaN   NaN   NaN  NaN  English
Man Among Cheetahs              2017   NaN  NaN   NaN   NaN  NaN  English
In Beaver Valley                1950   NaN  NaN   NaN   NaN  NaN  English

                                                                       \
Age                                                 13+  16+      18+
Title
Inception                       English,Japanese,French  NaN      NaN
The Matrix                                          NaN  NaN  English
Avengers: Infinity War                          English  NaN      NaN
Back to the Future                                  NaN  NaN      NaN
The Good, the Bad and the Ugly                      NaN  NaN  Italian
...                                                 ...  ...      ...
The Ghosts of Buxley Hall                           NaN  NaN      NaN
The Poof Point                                      NaN  NaN      NaN
Sharks of Lost Island                               NaN  NaN      NaN
Man Among Cheetahs                                  NaN  NaN      NaN
In Beaver Valley                                    NaN  NaN      NaN


Age                                  7+  all
Title
Inception                           NaN  NaN
The Matrix                          NaN  NaN
Avengers: Infinity War              NaN  NaN
Back to the Future              English  NaN
The Good, the Bad and the Ugly      NaN  NaN
...                                 ...  ...
The Ghosts of Buxley Hall           NaN  NaN
The Poof Point                  English  NaN
Sharks of Lost Island               NaN  NaN
Man Among Cheetahs                  NaN  NaN
In Beaver Valley                    NaN  NaN

[16744 rows x 12 columns]

### 4: Netflix screened movies based on language, runtime, and country

In [7]:
# Determine the movies, language, runtime and country screened by Netflix
mov_ott.pivot(index = 'Title', columns = 'Netflix',
             values = ['Runtime', 'Language', 'Country'])

                               Runtime                        Language  \
Netflix                              0      1                        0
Title
Inception                        148.0    NaN  English,Japanese,French
The Matrix                       136.0    NaN                  English
Avengers: Infinity War           149.0    NaN                  English
Back to the Future                 NaN  116.0                      NaN
The Good, the Bad and the Ugly   161.0    NaN                  Italian
...                                ...    ...                      ...
The Ghosts of Buxley Hall        120.0    NaN                  English
The Poof Point                    90.0    NaN                  English
Sharks of Lost Island              NaN    NaN                  English
Man Among Cheetahs                 NaN    NaN                  English
In Beaver Valley                   NaN   32.0                      NaN

                                                              Country  \
Netflix                               1                             0
Title
Inception                           NaN  United States,United Kingdom
The Matrix                          NaN                 United States
Avengers: Infinity War              NaN                 United States
Back to the Future              English                           NaN
The Good, the Bad and the Ugly      NaN      Italy,Spain,West Germany
...                                 ...                           ...
The Ghosts of Buxley Hall           NaN                 United States
The Poof Point                      NaN                 United States
Sharks of Lost Island               NaN                 United States
Man Among Cheetahs                  NaN                 United States
In Beaver Valley                English                           NaN


Netflix                                     1
Title
Inception                                 NaN
The Matrix                                NaN
Avengers: Infinity War                    NaN
Back to the Future              United States
The Good, the Bad and the Ugly            NaN
...                                       ...
The Ghosts of Buxley Hall                 NaN
The Poof Point                            NaN
Sharks of Lost Island                     NaN
Man Among Cheetahs                        NaN
In Beaver Valley                United States

[16744 rows x 6 columns]

### 5: The title of movies, specified language, potential runtime, and genres by content rating

In [8]:
# Determine the movies, language, runtime, and genres per age group
mov_ott.pivot(index = 'Title', columns = 'Age', 
              values = ['Runtime', 'Language', 'Genres'])

                               Runtime                                 \
Age                                NaN    13+  16+    18+     7+  all
Title
Inception                          NaN  148.0  NaN    NaN    NaN  NaN
The Matrix                         NaN    NaN  NaN  136.0    NaN  NaN
Avengers: Infinity War             NaN  149.0  NaN    NaN    NaN  NaN
Back to the Future                 NaN    NaN  NaN    NaN  116.0  NaN
The Good, the Bad and the Ugly     NaN    NaN  NaN  161.0    NaN  NaN
...                                ...    ...  ...    ...    ...  ...
The Ghosts of Buxley Hall        120.0    NaN  NaN    NaN    NaN  NaN
The Poof Point                     NaN    NaN  NaN    NaN   90.0  NaN
Sharks of Lost Island              NaN    NaN  NaN    NaN    NaN  NaN
Man Among Cheetahs                 NaN    NaN  NaN    NaN    NaN  NaN
In Beaver Valley                  32.0    NaN  NaN    NaN    NaN  NaN

                               Language                                \
Age                                 NaN                      13+  16+
Title
Inception                           NaN  English,Japanese,French  NaN
The Matrix                          NaN                      NaN  NaN
Avengers: Infinity War              NaN                  English  NaN
Back to the Future                  NaN                      NaN  NaN
The Good, the Bad and the Ugly      NaN                      NaN  NaN
...                                 ...                      ...  ...
The Ghosts of Buxley Hall       English                      NaN  NaN
The Poof Point                      NaN                      NaN  NaN
Sharks of Lost Island           English                      NaN  NaN
Man Among Cheetahs              English                      NaN  NaN
In Beaver Valley                English                      NaN  NaN

                                                       \
Age                                 18+       7+  all
Title
Inception                           NaN      NaN  NaN
The Matrix                      English      NaN  NaN
Avengers: Infinity War              NaN      NaN  NaN
Back to the Future                  NaN  English  NaN
The Good, the Bad and the Ugly  Italian      NaN  NaN
...                                 ...      ...  ...
The Ghosts of Buxley Hall           NaN      NaN  NaN
The Poof Point                      NaN  English  NaN
Sharks of Lost Island               NaN      NaN  NaN
Man Among Cheetahs                  NaN      NaN  NaN
In Beaver Valley                    NaN      NaN  NaN

                                                      Genres  \
Age                                                      NaN
Title
Inception                                                NaN
The Matrix                                               NaN
Avengers: Infinity War                                   NaN
Back to the Future                                       NaN
The Good, the Bad and the Ugly                           NaN
...                                                      ...
The Ghosts of Buxley Hall       Comedy,Family,Fantasy,Horror
The Poof Point                                           NaN
Sharks of Lost Island                            Documentary
Man Among Cheetahs                               Documentary
In Beaver Valley                    Documentary,Short,Family

                                                                       \
Age                                                          13+  16+
Title
Inception                       Action,Adventure,Sci-Fi,Thriller  NaN
The Matrix                                                   NaN  NaN
Avengers: Infinity War                   Action,Adventure,Sci-Fi  NaN
Back to the Future                                           NaN  NaN
The Good, the Bad and the Ugly                               NaN  NaN
...                                                          ...  ...
The Ghosts of Buxley Hall                                    NaN  NaN
The Poof Point                                               NaN  NaN
Sharks of Lost Island                                        NaN  NaN
Man Among Cheetahs                                           NaN  NaN
In Beaver Valley                                             NaN  NaN


Age                                       18+                       7+  all
Title
Inception                                 NaN                      NaN  NaN
The Matrix                      Action,Sci-Fi                      NaN  NaN
Avengers: Infinity War                    NaN                      NaN  NaN
Back to the Future                        NaN  Adventure,Comedy,Sci-Fi  NaN
The Good, the Bad and the Ugly        Western                      NaN  NaN
...                                       ...                      ...  ...
The Ghosts of Buxley Hall                 NaN                      NaN  NaN
The Poof Point                            NaN     Comedy,Family,Sci-Fi  NaN
Sharks of Lost Island                     NaN                      NaN  NaN
Man Among Cheetahs                        NaN                      NaN  NaN
In Beaver Valley                          NaN                      NaN  NaN

[16744 rows x 18 columns]